name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v2

            - name: Node 18.x
              uses: actions/setup-node@v2
              with:
                  node-version: '18.x'

            - name: npm install
              run: npm install

            - name: Compile Typescript
              run: tsc

            - name: copy files to server
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  target: ${{ secrets.TARGET }}
                  source: ./dist/*
                  strip_components: 1

            - name: SSH into Server and Restart Service
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: |
                      echo ${{ secrets.PASSWORD }} | sudo -S service dc-lurker-backend restart
